# Generated by quarto-emit.
# Source: /tmp/quarto-render.aSBLetzc/project/notebooks/infrastructure/14_page-uvr.qmd
# Do not edit directly unless you intend to stop using this document as the source of truth.

local({
  uvr_library <- Sys.getenv("UVR_LIBRARY", file.path(getwd(), ".uvr", "library"))
  uvr_library <- normalizePath(uvr_library, mustWork = FALSE)
  if (dir.exists(uvr_library)) {
    .libPaths(unique(c(uvr_library, .libPaths())))
  }
  Sys.setenv(R_LIBS_USER = uvr_library, R_LIBS = uvr_library)
})
