# WARNING - Generated by {fusen} from dev/flat_build_targets_pipeline.Rmd: do not edit by hand # nolint: line_length_linter.

#' Dynamically build the targets pipeline for the project.
#' 
#' @param targets_notebook_name Character. The name of the local targets notebook file to create. Default is `"_target_notebook.Rmd"`.
#' @param targets_file_name Character. The name of the local targets file to create. Default is `"_targets.R"`.
#' @param pkg_name Character. This package, `"NepalClimateHealth"`.
#' @param vignette_name Character. The name of the vignette in the package that defines the targets notebook. Default is `"pipeline-definition"`.
#' @param overwrite Logical. Whether to overwrite existing files. Default is `FALSE`.
#' 
#' @return Invisible `NULL`. The function is called for its side effects of creating files.
#' 
#' @details
#' This function sets up the targets pipeline by defining a local `_targets.R` file
#' and using `tar_tangle()` to create the necessary targets from an Rmd file.
#' The Rmd file is, itself, the vignette \code{vignette("pipeline-definition", package = "NepalClimateHealth")}.
#' Note that the function checks for the presence of required packages and alerts the user if any are missing,
#' because they are necessary to build the pipeline from the vignette locally.
#' 
#' @importFrom glue glue
#' @importFrom here here
#' @importFrom fs file_copy file_exists path
#' @importFrom cli cli_alert_success cli_alert_info cli_alert_danger
#' @importFrom readr read_lines write_lines
#' @importFrom stringr str_subset
#' @importFrom xfun gsub_file
#' @import knitr rmarkdown skimr dplyr tarchetypes targets
#' @export
#' @examples
#' #build_targets_pipeline()
build_targets_pipeline <- function(
  targets_notebook_name = "_target_notebook.Rmd", 
  targets_file_name = "_targets.R", 
  pkg_name = "KiribatiBiomarkers", 
  vignette_name = "pipeline-definition.Rmd",
  overwrite = FALSE
  ) {

  # assert existence of SUGGESTS packages necessary on the user's end
  # required_packages <- c("knitr", "rmarkdown", "sf", "skimr", "testthat", "dplyr", "tarchetypes", "targets")
  # missing_packages <- required_packages[!sapply(required_packages, requireNamespace, quietly = TRUE)]
  # if(length(missing_packages) > 0){
  #   cli_alert_danger("The following required packages are missing: {paste(missing_packages, collapse = ', ')}. I recommend installing them or else this may not work.")
  # }
  
  # Define the path to the targets notebook definition and file
  targets_notebook <- here(targets_notebook_name)
  targets_file <- here(targets_file_name)

  # fetch this installed vignette
  # v <- vignette(vignette_name, package = pkg_name)
  # vignette_path <- path(v$Dir, "doc", v$File)

  vignette_path <- system.file(vignette_name, package = pkg_name)
  
  # assert that the vignette exists
  if (!file_exists(vignette_path)) {
    cli_alert_danger("Vignette '{vignette_name}' not found in package '{pkg_name}'.")
    stop("Cannot proceed without the vignette file.")
  }

  # copy to local project
  file_copy(vignette_path, targets_notebook, overwrite = overwrite)
  # remove irrelevant quarto directives
  lines <- read_lines(targets_notebook) %>%
    str_subset("#\\| eval: no", negate = TRUE)
  writeLines(lines, targets_notebook)
  cli_alert_success("Created local targets notebook file at: {targets_notebook}")

  # fetch the installed template for _targets.R
  template_path <- system.file("_targets.R", package = pkg_name)

  # copy to local project
  file_copy(template_path, targets_file, overwrite = overwrite)
  cli_alert_success("Created local targets file at: {targets_file}")

  # replace the tar_tangle() default to use the local notebook name
  if(targets_notebook_name != "_target_notebook.Rmd") {
    
    gsub_file(
      targets_file,
      pattern = "_target_notebook.Rmd",
      replacement = targets_notebook_name
    )
    cli_alert_success("Updated targets file to use targets notebook as: {targets_notebook_name}")
    
  }

  cli_alert_info("To build the base pipeline, run `targets::tar_make()` in your R console. Use `targets::tar_read()` or `targets::tar_load()` to access target outputs.")
  cli_alert_info("You can also edit the targets file to extend the pipeline as needed for your project.")

  return(invisible())
}
