# Generated by quarto-emit.
# Source: /tmp/quarto-render.kZlq3rY3/project/notebooks/pipeline/17_page-execute-pipeline.qmd
# Do not edit directly unless you intend to stop using this document as the source of truth.

library(targets)
library(here)

source("pipeline/curate_biomarkers.R")

base_targets <- list(
  tar_target(
    stagecoach_manifest,
    here::here("stagecoach_manifest.yml"),
    format = "file"
  ),
  tar_target(
    raw_inputs,
    {
      input_dir <- here::here("data", "inputs")
      if (!dir.exists(input_dir)) {
        stop("Staged input directory is missing: ", input_dir)
      }

      inputs <- list.files(
        input_dir,
        recursive = TRUE,
        full.names = TRUE,
        include.dirs = FALSE,
        no.. = TRUE
      )
      if (!length(inputs)) {
        stop("No staged input files are available in: ", input_dir)
      }

      inputs
    },
    format = "file"
  )
)

c(base_targets, curation_targets())
