# Generated by quarto-emit.
# Source: /tmp/quarto-render.kZlq3rY3/project/notebooks/pipeline/16_page-targets-curation.qmd
# Do not edit directly unless you intend to stop using this document as the source of truth.

# Dependencies are namespace-qualified so this module can be sourced by the
# generated pipeline without creating another package-level source of truth.

curation_required_columns <- c(
  "DOB_HIES", "date_of_interview", "hhld_id_hm_basic__id", "L1_q61_hdl",
  "ldl_corrected", "tc_corrected", "pulse_corrected", "glucose_corrected",
  "triglycerides_corrected", "systolic_corrected", "diastolic_corrected",
  "temperature_correctedF", "hemoglobin_corrected", "hematocrit_corrected",
  "diabetes_corrected", "age_group", "fever", "BloodPressure_status",
  "Glucose_status", "anemia_status", "cholesterol_status",
  "triglycerides_status", "diabetes_status", "gender_HIES", "L1_q3_gender",
  "L1_q125_which_community_are_you_in", "L1_q124_which_island_are_we_on"
)

curation_input_paths <- function(raw_inputs) {
  biomarker_paths <- raw_inputs[
    grepl("Goldenetal_KI_biomarkers", raw_inputs) &
      basename(raw_inputs) == "kiribati_cleandata_mergedHIES.csv"
  ]
  village_paths <- raw_inputs[
    grepl("village_metadata", basename(raw_inputs), ignore.case = TRUE) &
      grepl("\\.csv$", raw_inputs, ignore.case = TRUE)
  ]

  if (length(biomarker_paths) != 1L) {
    stop(
      "Expected exactly one Golden et al. biomarker export; found ",
      length(biomarker_paths), ". Refine the staged input inventory."
    )
  }
  if (length(village_paths) != 1L) {
    stop(
      "Expected exactly one village_metadata CSV; found ",
      length(village_paths), ". Refine the staged input inventory."
    )
  }

  c(biomarkers = biomarker_paths, village_metadata = village_paths)
}

assert_required_columns <- function(data, required, dataset_name) {
  missing <- setdiff(required, names(data))
  if (length(missing)) {
    stop(
      dataset_name, " is missing required columns: ",
      paste(missing, collapse = ", ")
    )
  }
  invisible(data)
}

add_age_in_months <- function(data) {
  assert_required_columns(
    data,
    c("DOB_HIES", "date_of_interview"),
    "Biomarker export"
  )

  data |>
    dplyr::mutate(
      dob = as.Date(.data[["DOB_HIES"]], format = "%d/%m/%Y"),
      interview_date = as.Date(
        .data[["date_of_interview"]],
        format = "%d/%m/%Y"
      ),
      age_in_months = lubridate::interval(dob, interview_date) /
        lubridate::months(1)
    )
}

curation_audit <- function(data_with_age) {
  tibble::tibble(
    metric = c("source_rows", "missing_dates", "nonpositive_age_rows"),
    value = c(
      nrow(data_with_age),
      sum(is.na(data_with_age$dob) | is.na(data_with_age$interview_date)),
      sum(is.na(data_with_age$age_in_months) | data_with_age$age_in_months <= 0)
    )
  )
}

hash_identifier <- function(identifier) {
  vapply(as.character(identifier), digest::digest, character(1))
}

curate_slimmed_data <- function(data_with_age) {
  assert_required_columns(data_with_age, curation_required_columns, "Biomarker export")

  data_with_age |>
    dplyr::filter(!is.na(age_in_months), age_in_months > 0) |>
    dplyr::transmute(
      uid = hash_identifier(.data[["hhld_id_hm_basic__id"]]),
      hdl = .data[["L1_q61_hdl"]], ldl = .data[["ldl_corrected"]],
      tc = .data[["tc_corrected"]], pulse = .data[["pulse_corrected"]],
      glucose = .data[["glucose_corrected"]],
      triglycerides = .data[["triglycerides_corrected"]],
      systolic = .data[["systolic_corrected"]],
      diastolic = .data[["diastolic_corrected"]],
      temperature = .data[["temperature_correctedF"]],
      hemoglobin = .data[["hemoglobin_corrected"]],
      hematocrit = .data[["hematocrit_corrected"]],
      diabetes = .data[["diabetes_corrected"]], age_group = .data[["age_group"]],
      fever = .data[["fever"]],
      BloodPressure_status = .data[["BloodPressure_status"]],
      Glucose_status = .data[["Glucose_status"]],
      anemia_status = .data[["anemia_status"]],
      cholesterol_status = .data[["cholesterol_status"]],
      triglycerides_status = .data[["triglycerides_status"]],
      diabetes_status = .data[["diabetes_status"]],
      gender = .data[["gender_HIES"]], age_in_months
    ) |>
    dplyr::mutate(
      dplyr::across(where(is.character), as.factor),
      uid = as.character(uid)
    )
}

curate_small_data <- function(data_with_age, village_metadata) {
  assert_required_columns(
    village_metadata,
    c("village", "island", "village_id", "rururb"),
    "Village metadata"
  )

  data_with_age |>
    dplyr::filter(!is.na(age_in_months), age_in_months > 0) |>
    dplyr::transmute(
      uid = hash_identifier(.data[["hhld_id_hm_basic__id"]]), age_in_months,
      gender = .data[["L1_q3_gender"]],
      community = .data[["L1_q125_which_community_are_you_in"]],
      island = .data[["L1_q124_which_island_are_we_on"]]
    ) |>
    dplyr::left_join(
      dplyr::select(village_metadata, village, island, village_id, rururb),
      by = c("community" = "village", "island" = "island")
    ) |>
    dplyr::select(uid, age_in_months, gender, village_id, rururb) |>
    dplyr::mutate(
      dplyr::across(where(is.character), as.factor),
      uid = as.character(uid)
    )
}

slimmed_labels <- c(
  uid = "De-identified record identifier", hdl = "HDL cholesterol",
  ldl = "LDL cholesterol", tc = "Total cholesterol", pulse = "Pulse",
  glucose = "Glucose", triglycerides = "Triglycerides",
  systolic = "Systolic blood pressure", diastolic = "Diastolic blood pressure",
  temperature = "Temperature in Fahrenheit", hemoglobin = "Hemoglobin level",
  hematocrit = "Percentage of red blood cells", diabetes = "HbA1c level",
  age_group = "Age group", fever = "Fever recorded",
  BloodPressure_status = "Blood pressure status", Glucose_status = "Glucose status",
  anemia_status = "Anemia status", cholesterol_status = "Cholesterol status",
  triglycerides_status = "Triglycerides status", diabetes_status = "Diabetes status",
  gender = "Gender", age_in_months = "Age in months at interview"
)

small_labels <- c(
  uid = "De-identified record identifier",
  age_in_months = "Age in months at interview", gender = "Gender",
  village_id = "Approved non-identifying village key",
  rururb = "Village rural/urban classification"
)

write_release_csv <- function(data, path) {
  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
  readr::write_csv(data, path)
  path
}

write_data_dictionary <- function(data, labels, path) {
  labelled::var_label(data) <- as.list(labels[names(data)])
  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
  readr::write_csv(codebook::codebook_table(data), path)
  path
}

curation_targets <- function() {
  output_dir <- file.path("data", "outputs", "curated")

  list(
    targets::tar_target(
      curation_inputs, curation_input_paths(raw_inputs), format = "file"
    ),
    targets::tar_target(
      curation_source,
      readr::read_csv(curation_inputs[["biomarkers"]], show_col_types = FALSE)
    ),
    targets::tar_target(
      village_metadata,
      readr::read_csv(curation_inputs[["village_metadata"]], show_col_types = FALSE)
    ),
    targets::tar_target(curation_source_with_age, add_age_in_months(curation_source)),
    targets::tar_target(curation_audit_table, curation_audit(curation_source_with_age)),
    targets::tar_target(slimmed_data, curate_slimmed_data(curation_source_with_age)),
    targets::tar_target(
      small_data, curate_small_data(curation_source_with_age, village_metadata)
    ),
    targets::tar_target(
      slimmed_data_csv,
      write_release_csv(slimmed_data, file.path(output_dir, "slimmed_data.csv")),
      format = "file"
    ),
    targets::tar_target(
      small_data_csv,
      write_release_csv(small_data, file.path(output_dir, "small_data.csv")),
      format = "file"
    ),
    targets::tar_target(
      slimmed_data_dictionary_csv,
      write_data_dictionary(
        slimmed_data, slimmed_labels,
        file.path(output_dir, "data_dictionary_slimmed_data.csv")
      ),
      format = "file"
    ),
    targets::tar_target(
      small_data_dictionary_csv,
      write_data_dictionary(
        small_data, small_labels,
        file.path(output_dir, "data_dictionary_small_data.csv")
      ),
      format = "file"
    ),
    targets::tar_target(
      curation_audit_csv,
      write_release_csv(
        curation_audit_table, file.path(output_dir, "curation_audit.csv")
      ),
      format = "file"
    )
  )
}
