[project]
name = "KiribatiBiomarkers"
description = "Kiribati Biomarkers Data Distribution Package"

[dependencies]
Matrix = "*"
R6 = "*"
Rcpp = "*"
askpass = "*"
attachment = "*"
backports = "*"
base64enc = "*"
base64url = "*"
bit = "*"
bit64 = "*"
brew = "*"
brio = "*"
bslib = "*"
cachem = "*"
callr = "*"
cli = "*"
clipr = "*"
codetools = "*"
commonmark = "*"
config = "*"
cpp11 = "*"
crayon = "*"
credentials = "*"
curl = "*"
"data.table" = "*"
desc = "*"
devtools = "*"
diffobj = "*"
digest = "*"
downlit = "*"
dplyr = "*"
ellipsis = "*"
evaluate = "*"
fansi = "*"
fastmap = "*"
fontawesome = "*"
fs = "*"
fusen = "*"
generics = "*"
gert = "*"
gh = "*"
gitcreds = "*"
glue = "*"
here = "*"
highr = "*"
hms = "*"
htmltools = "*"
htmlwidgets = "*"
httpuv = "*"
httr2 = "*"
igraph = "*"
ini = "*"
jquerylib = "*"
jsonlite = "*"
knitr = "*"
later = "*"
lattice = "*"
lifecycle = "*"
lightparser = "*"
magrittr = "*"
memoise = "*"
mime = "*"
miniUI = "*"
openssl = "*"
pillar = "*"
pkgbuild = "*"
pkgconfig = "*"
pkgdown = "*"
pkgload = "*"
praise = "*"
prettyunits = "*"
processx = "*"
profvis = "*"
progress = "*"
promises = "*"
ps = "*"
purrr = "*"
ragg = "*"
rappdirs = "*"
rcmdcheck = "*"
readr = "*"
remotes = "*"
renv = "*"
repr = "*"
rlang = "*"
rmarkdown = "*"
roxygen2 = "*"
rprojroot = "*"
rstudioapi = "*"
rversions = "*"
sass = "*"
secretbase = "*"
sessioninfo = "*"
shiny = "*"
skimr = "*"
sourcetools = "*"
stats = "*"
stringi = "*"
stringr = "*"
sys = "*"
systemfonts = "*"
tarchetypes = "*"
targets = "*"
testthat = "*"
textshaping = "*"
tibble = "*"
tidyr = "*"
tidyselect = "*"
tinytex = "*"
tzdb = "*"
urlchecker = "*"
usethis = "*"
utf8 = "*"
vctrs = "*"
vroom = "*"
waldo = "*"
whisker = "*"
withr = "*"
xfun = "*"
xml2 = "*"
xopen = "*"
xtable = "*"
yaml = "*"
zip = "*"

[dev-dependencies]
testthat = "*"
