---
title: "Project Contract"
execute:
  eval: false
engine: markdown
---

This page defines the different components of the project and emits
those necessary, focusing primarily on folder creation and assignment.

The project initially uses the Cookie Cutter Data Science layout, but hinges on
Quarto Manuals' `/notebooks` directory for its functionality.

- `/containers` houses all container artifacts; `.sif` files are ignored;
- `/data` uses 3 subfolders -- `inputs`, `interim`, and `outputs`, where the first are
staged using `stagecoach`, the `interim` is for ephemeral data that
can be discarded, and `outputs` is used for data that ultimately gets versioned
and shared;

- `/docs` houses the docs for the project, generated by `quarto render notebooks`

- `/notebooks` drives development of this manual

- `/scripts` drives execution of this manual, including container runtime helpers
 
::: {.manual-prereq title="Confirm Directories Exist"}

There aren't any specific checks necessary before running this procedure.

You just need to ensure that the root directory for this repo is writable.

::: 

:::{.manual-procedure title="Materialize Folders"}

Run the following to materialize the necessary folder:

```sh
mkdir -p containers data/inputs data/intermediates data/outputs docs notebooks scripts  
```

:::{.manual-check title="Verify Necessary Folders"}

A shell test block here would be useful:

#TODO.

:::
