# Generated by quarto-emit.
# Source: /n/holylabs/cgolden_lab/Lab/frontier/works/prospectors/prospectorKiribatiBioMarkers/notebooks/01_misc-render-isolated.qmd
# Do not edit directly unless you intend to stop using this document as the source of truth.

#!/usr/bin/env bash
# Render the Manual in a private staging copy. Forward any arguments to
# `quarto render notebooks`; this avoids contention for notebooks/.quarto/_freeze.
#
# Usage:
#   scripts/render-isolated.sh [quarto-render-argument ...]
#
# Example:
#   scripts/render-isolated.sh --profile authoring
set -euo pipefail

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
project_dir=$(cd "$script_dir/.." && pwd)
stage_dir=$(mktemp -d "${TMPDIR:-/tmp}/quarto-render.XXXXXXXX")
trap 'rm -rf -- "$stage_dir"' EXIT

# Quarto's Sass cache is a Deno KV database normally kept under ~/.cache.
# Keep all XDG state in the staging directory so concurrent jobs do not share
# that database.
export XDG_CACHE_HOME="$stage_dir/xdg-cache"
export XDG_DATA_HOME="$stage_dir/xdg-data"
export XDG_RUNTIME_DIR="$stage_dir/xdg-runtime"
mkdir -p "$XDG_CACHE_HOME" "$XDG_DATA_HOME" "$XDG_RUNTIME_DIR"

# Give this render a new notebooks/.quarto directory. Do not copy generated
# site output or prior notebook render state into the staging project.
rsync -a \
  --exclude '.git' \
  --exclude '.jj' \
  --exclude 'docs' \
  --exclude 'notebooks/.quarto' \
  --exclude 'notebooks/_site' \
  --exclude 'notebooks/site_libs' \
  "$project_dir/" "$stage_dir/project/"

(
  cd "$stage_dir/project"
  quarto render notebooks "$@"
)

# docs/ is this Quarto project's configured output directory. Promote only a
# successful staged render; --delete keeps the published site exact.
rsync -a --delete "$stage_dir/project/docs/" "$project_dir/docs/"
